# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Multiplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=40)),
                ('currency_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_one', to='currency.Currency')),
                ('currency_second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_second', to='currency.Currency')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='multiplier',
            unique_together=set([('currency_one', 'currency_second')]),
        ),
    ]
