# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20161022_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplier',
            old_name='currency_one',
            new_name='currency_first',
        ),
        migrations.AlterUniqueTogether(
            name='multiplier',
            unique_together=set([('currency_first', 'currency_second')]),
        ),
    ]
