# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20161022_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplier',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
